### ISSUE TITLE
ℋ ✨ Return Of The Max ✨ 󠁴󠁭󠁢󠁿 Ỵ

### ISSUE THREAD

**Issue by mik25** [danamag/stremio-addons-list#153]
### Addon Manifest URL

https://hrotmy.pages.dev/manifest.json

### Addon Description

MIXED IPTV WORLD STREAMS

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by grande196** [comment]
No portuguese channels 😟😭

**Comment by frankycolumbo007** [comment]
Lots and lots and lots of "playback error" and channels without sound

**Comment by KumaMechaSama** [comment]
Thanks for the coming back!

Regarding the connection for the channels in France: there are Italian channels in there; 
Also, there are no longer the Amazon Prime channels or Bein sport as before; 
is it possible to rectify all that? Please

As usual, sometimes some channels work, others don't, but that's the way it is and I suppose it's difficult to keep dozens of channels from several countries active.

Thank you very much

**Comment by challou77** [comment]
hi when I watch Netherlands Zanders , it keeps zapping to the next channel by itself , I can not keep watching on one channel

**Comment by mikmc55** [comment]
All should be working

**Comment by Zeunas** [comment]
Still not working for me, I've tried diff countries and all channels say 'playback error'

**Comment by owen-the-kid** [comment]
> Still not working for me, I've tried diff countries and all channels say 'playback error'

the same is happening to me the last few days

**Comment by KumaMechaSama** [comment]
Same thing, having tested several countries, nothing works any more. Let's wait for a corrective update

**Comment by 77sa77** [comment]
same thing, "playback error"

**Comment by KumaMechaSama** [comment]
It seems to be working again for some of the countries I tested

**Comment by ESC4NOR** [comment]
doesnt work, playback error

**Comment by Stofcri** [comment]
Doesn’t work 26 august 2023
